// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/server/proto/handlers.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []byte                 `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUpdatesRequest) Reset() {
	*x = PostUpdatesRequest{}
	mi := &file_internal_server_proto_handlers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUpdatesRequest) ProtoMessage() {}

func (x *PostUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_handlers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUpdatesRequest.ProtoReflect.Descriptor instead.
func (*PostUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_handlers_proto_rawDescGZIP(), []int{0}
}

func (x *PostUpdatesRequest) GetMetrics() []byte {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type PostUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // ошибка
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUpdatesResponse) Reset() {
	*x = PostUpdatesResponse{}
	mi := &file_internal_server_proto_handlers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUpdatesResponse) ProtoMessage() {}

func (x *PostUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_handlers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUpdatesResponse.ProtoReflect.Descriptor instead.
func (*PostUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_handlers_proto_rawDescGZIP(), []int{1}
}

func (x *PostUpdatesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_server_proto_handlers_proto protoreflect.FileDescriptor

const file_internal_server_proto_handlers_proto_rawDesc = "" +
	"\n" +
	"$internal/server/proto/handlers.proto\x12\vserver_grpc\".\n" +
	"\x12PostUpdatesRequest\x12\x18\n" +
	"\ametrics\x18\x01 \x01(\fR\ametrics\"+\n" +
	"\x13PostUpdatesResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\\\n" +
	"\bHandlers\x12P\n" +
	"\vPostUpdates\x12\x1f.server_grpc.PostUpdatesRequest\x1a .server_grpc.PostUpdatesResponseB\x17Z\x15internal/server/protob\x06proto3"

var (
	file_internal_server_proto_handlers_proto_rawDescOnce sync.Once
	file_internal_server_proto_handlers_proto_rawDescData []byte
)

func file_internal_server_proto_handlers_proto_rawDescGZIP() []byte {
	file_internal_server_proto_handlers_proto_rawDescOnce.Do(func() {
		file_internal_server_proto_handlers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_server_proto_handlers_proto_rawDesc), len(file_internal_server_proto_handlers_proto_rawDesc)))
	})
	return file_internal_server_proto_handlers_proto_rawDescData
}

var file_internal_server_proto_handlers_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_server_proto_handlers_proto_goTypes = []any{
	(*PostUpdatesRequest)(nil),  // 0: server_grpc.PostUpdatesRequest
	(*PostUpdatesResponse)(nil), // 1: server_grpc.PostUpdatesResponse
}
var file_internal_server_proto_handlers_proto_depIdxs = []int32{
	0, // 0: server_grpc.Handlers.PostUpdates:input_type -> server_grpc.PostUpdatesRequest
	1, // 1: server_grpc.Handlers.PostUpdates:output_type -> server_grpc.PostUpdatesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_server_proto_handlers_proto_init() }
func file_internal_server_proto_handlers_proto_init() {
	if File_internal_server_proto_handlers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_server_proto_handlers_proto_rawDesc), len(file_internal_server_proto_handlers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_server_proto_handlers_proto_goTypes,
		DependencyIndexes: file_internal_server_proto_handlers_proto_depIdxs,
		MessageInfos:      file_internal_server_proto_handlers_proto_msgTypes,
	}.Build()
	File_internal_server_proto_handlers_proto = out.File
	file_internal_server_proto_handlers_proto_goTypes = nil
	file_internal_server_proto_handlers_proto_depIdxs = nil
}
