// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/server/proto/handlers.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_internal_server_proto_handlers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_handlers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_handlers_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PostUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUpdatesRequest) Reset() {
	*x = PostUpdatesRequest{}
	mi := &file_internal_server_proto_handlers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUpdatesRequest) ProtoMessage() {}

func (x *PostUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_handlers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUpdatesRequest.ProtoReflect.Descriptor instead.
func (*PostUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_handlers_proto_rawDescGZIP(), []int{1}
}

func (x *PostUpdatesRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type PostUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // ошибка
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUpdatesResponse) Reset() {
	*x = PostUpdatesResponse{}
	mi := &file_internal_server_proto_handlers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUpdatesResponse) ProtoMessage() {}

func (x *PostUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_handlers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUpdatesResponse.ProtoReflect.Descriptor instead.
func (*PostUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_handlers_proto_rawDescGZIP(), []int{2}
}

func (x *PostUpdatesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueRequest) Reset() {
	*x = GetValueRequest{}
	mi := &file_internal_server_proto_handlers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueRequest) ProtoMessage() {}

func (x *GetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_handlers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueRequest.ProtoReflect.Descriptor instead.
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_handlers_proto_rawDescGZIP(), []int{3}
}

func (x *GetValueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueResponse) Reset() {
	*x = GetValueResponse{}
	mi := &file_internal_server_proto_handlers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueResponse) ProtoMessage() {}

func (x *GetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_proto_handlers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueResponse.ProtoReflect.Descriptor instead.
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return file_internal_server_proto_handlers_proto_rawDescGZIP(), []int{4}
}

func (x *GetValueResponse) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

var File_internal_server_proto_handlers_proto protoreflect.FileDescriptor

const file_internal_server_proto_handlers_proto_rawDesc = "" +
	"\n" +
	"$internal/server/proto/handlers.proto\x12\vserver_grpc\"\x1c\n" +
	"\x06Metric\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"C\n" +
	"\x12PostUpdatesRequest\x12-\n" +
	"\ametrics\x18\x01 \x03(\v2\x13.server_grpc.MetricR\ametrics\"+\n" +
	"\x13PostUpdatesResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"!\n" +
	"\x0fGetValueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x10GetValueResponse\x12+\n" +
	"\x06metric\x18\x01 \x01(\v2\x13.server_grpc.MetricR\x06metric2\xa5\x01\n" +
	"\bHandlers\x12P\n" +
	"\vPostUpdates\x12\x1f.server_grpc.PostUpdatesRequest\x1a .server_grpc.PostUpdatesResponse\x12G\n" +
	"\bGetValue\x12\x1c.server_grpc.GetValueRequest\x1a\x1d.server_grpc.GetValueResponseB\x17Z\x15internal/server/protob\x06proto3"

var (
	file_internal_server_proto_handlers_proto_rawDescOnce sync.Once
	file_internal_server_proto_handlers_proto_rawDescData []byte
)

func file_internal_server_proto_handlers_proto_rawDescGZIP() []byte {
	file_internal_server_proto_handlers_proto_rawDescOnce.Do(func() {
		file_internal_server_proto_handlers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_server_proto_handlers_proto_rawDesc), len(file_internal_server_proto_handlers_proto_rawDesc)))
	})
	return file_internal_server_proto_handlers_proto_rawDescData
}

var file_internal_server_proto_handlers_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_server_proto_handlers_proto_goTypes = []any{
	(*Metric)(nil),              // 0: server_grpc.Metric
	(*PostUpdatesRequest)(nil),  // 1: server_grpc.PostUpdatesRequest
	(*PostUpdatesResponse)(nil), // 2: server_grpc.PostUpdatesResponse
	(*GetValueRequest)(nil),     // 3: server_grpc.GetValueRequest
	(*GetValueResponse)(nil),    // 4: server_grpc.GetValueResponse
}
var file_internal_server_proto_handlers_proto_depIdxs = []int32{
	0, // 0: server_grpc.PostUpdatesRequest.metrics:type_name -> server_grpc.Metric
	0, // 1: server_grpc.GetValueResponse.metric:type_name -> server_grpc.Metric
	1, // 2: server_grpc.Handlers.PostUpdates:input_type -> server_grpc.PostUpdatesRequest
	3, // 3: server_grpc.Handlers.GetValue:input_type -> server_grpc.GetValueRequest
	2, // 4: server_grpc.Handlers.PostUpdates:output_type -> server_grpc.PostUpdatesResponse
	4, // 5: server_grpc.Handlers.GetValue:output_type -> server_grpc.GetValueResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_server_proto_handlers_proto_init() }
func file_internal_server_proto_handlers_proto_init() {
	if File_internal_server_proto_handlers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_server_proto_handlers_proto_rawDesc), len(file_internal_server_proto_handlers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_server_proto_handlers_proto_goTypes,
		DependencyIndexes: file_internal_server_proto_handlers_proto_depIdxs,
		MessageInfos:      file_internal_server_proto_handlers_proto_msgTypes,
	}.Build()
	File_internal_server_proto_handlers_proto = out.File
	file_internal_server_proto_handlers_proto_goTypes = nil
	file_internal_server_proto_handlers_proto_depIdxs = nil
}
